#!/usr/bin/env bash

# Place this script in /usr/local/bin and make it executable.
# $ cp install_zip.sh /usr/local/bin
# $ chmod 755 /usr/local/bin/install_zip
 
# The zipfile should be placed in the current directory or the
# full path for the zipfile must be provided.

# usage: install_zip.sh zipfile
#
# This script installs a Gnome Shell Extension zipfile.
#
# The functionality removed from the Gnome Tweak Tool in Gnome
# Shell version 3.26 is provided.

	
ZIPFILE="${1}"
if [ -f "${ZIPFILE}" ]; then
    TMPDIR=`mktemp -d`
    sleep 1
    unzip "${ZIPFILE}" -d "${TMPDIR}"
    cd "${TMPDIR}"
    UUID=`grep uuid ${TMPDIR}/metadata.json | sed s/[\",\ ]//g | cut -c6-99`
    EXTDIR="${HOME}/.local/share/gnome-shell/extensions/${UUID}/"
    if [ -d "${EXTDIR}" ]; then
        TMPSAVEDIR=`mktemp -d`
        mv "${EXTDIR}" "${TMPSAVEDIR}"
        echo " "
        echo  "OLD ${EXTDIR} SAVED IN ${TMPSAVEDIR}"
    fi 
    mkdir "${EXTDIR}"
    cp -r "${TMPDIR}"/* "${EXTDIR}"
    echo " "
    echo "Log out and re-login to restart session."
    echo "Use Tweak tool to enable and/or set preferences."
fi




